export const data = {
  name: "Nithin Kamal",
  title: "Machine Learning Engineer, Software Engineer, Full Stack Developer",
  sections: ["about", "skills", "timeline", "projects"],
  sectionTitles: ["ABOUT", "SKILLS", "EXPERIENCE", "PROJECTS"],
  about: {
    title:
      "AI/ML Engineer | Full Stack Developer, RWTH Aachen University '23, MSc in Robotics ",
    description: `I am a recent graduate of the Master’s program in Robotic Systems Engineering
    at RWTH Aachen University (AI/ML Specialization). I have a proven track record with more than 5 years of professional experience in software development,
    full-stack development and machine learning. `,
  },
  education: [
    "RWTH Aachen University, MSc in Robotics, 2023",
    "University of Kerala, B.Tech in Electronics & Communication, 2017",
    "TensorFlow Professional Developer Certificate, 2023",
  ],
  banner: ["RWTH.png", "BMW.png", "Fraunhofer-IKS.png"],
  skills: [
    {
      title: "Languages",
      items: ["Python", "TypeScript", "JavaScript", "C++", "Bash", "SQL"],
      boldIdx: 2,
      description:
        "I have been working with Python for more than 5 years and have experience in developing web applications using TypeScript and JavaScript.",
    },
    {
      title: "Artificial Intelligence & Machine Learning",
      smallTitle: "AI & ML",
      items: [
        "Computer Vision",
        "Deep Learning",
        "Generative AI",
        "PyTorch",
        "Tensorflow",
        "Large Language Models (LLM)",
        "Natural Language Processing",
        "OpenCV",
        "Pandas",
        "Numpy",
        "Keras",
        "SciKit-Learn",
        "Jupyter",
        "Data Analysis",
        "Numerical Optimization",
        "3D Images",
        "LangChain",
        "JAX",
      ],
      boldIdx: 5,
      description:
        "I have been working with AI/ML for more than 3 years and have experience in developing and deploying AI/ML models for various applications.",
    },
    {
      title: "Web Development",
      items: [
        "React",
        "Next.js",
        "Node.js",
        "Tailwind CSS",
        "Data Visualization",
        "REST API",
        "GraphQL",
        "Express.js",
        "HTML",
        "CSS",
        "Flask",
        "ES6",
        "Server Side Rendering",
      ],
      boldIdx: 5,
      description:
        "I have been working with web development for more than 5 years and have experience in developing and deploying web applications.",
    },
    {
      title: "DevOps & Cloud",
      items: [
        "Git",
        "Docker",
        "AWS",
        ,
        "CI/CD",
        "Windows",
        "Linux",
        "Microsoft Azure",
        "MQTT",
        "GitLab",
        "Vercel",
        "Jenkins",
        "Micorosft Azure",
      ],
      boldIdx: 3,
      description:
        "I have experience in end-to-end development and deployment of web applications and AI/ML models across professional work and personal projects which includes this very own portfolio website. This includes CI/CD, containerization, and cloud deployment. I have professional experience in AWS services like S3, EC2, Lambda, and Microsoft Azure.",
    },
    {
      title: "Databases",
      items: [
        "PostGreSQL",
        "MongoDB",
        "MySQL",
        "InfluxDB",
        "QuasarDB",
        "SQLite",
      ],
      boldIdx: 0,
      description:
        "I have experience in working with SQL and NoSQL databases for various applications.",
    },
    {
      title: "Methodology",
      items: [
        "Agile",
        "Test Driven Development",
        "Scrum",
        "Kanban",
        "Pair Programming",
        "Code Review",
      ],
      boldIdx: 0,
      description:
        "I have experience in working with Agile methodologies and have been part of various software development teams.",
    },
    {
      title: "Others",
      items: [
        "ROS (Robot Operating System)",
        "Data Structures and Algorithms",
        "JIRA",
        "Shell Script",
        "Gazebo",
        "LateX",
        "Microsoft Office",
        "Object Oriented Programming",
        "Functional Programming",
        "Design Patterns",
        "PyQt",
      ],
      boldIdx: 2,
      description:
        "I have experience in working with ROS and have experience in developing and deploying ROS nodes for various robotic applications. I am also proficient in data structures and algorithms and design patterns.",
    },
  ],
};
